services:
  mongodb:
    image: mongo:latest
    container_name: ai-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - ai-app-network
  
  sonarqube:
    image: sonarqube:latest
    container_name: ai-sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9005:9000"
    networks:
      - ai-app-network

  qdrant:
    image: qdrant/qdrant
    container_name: ai-qdrant
    ports:
      - "6333:6333" # REST API Portu
      - "6334:6334" # GRPC Portu
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always
    networks:
      - ai-app-network

networks:
  ai-app-network:
    driver: bridge

volumes:
  mongodb_data:
  qdrant_storage:
